const fs = require('fs/promises')

async function cron() {
  let content = `Just an autogenerated dummy file to prevent GitHub disabling the cron action :facepalm:
  
Last update: ${new Date().toISOString()}`

  await fs.writeFile('dummy.txt', content)
}

cron().catch((e) => console.log(e))
